version: '3.8'

services:
  tor-scout:
    build:
      context: .
      dockerfile: ./compose/local/scout/Dockerfile
      args:
        - DEV=true
    image: tor-scout
    container_name: tor-scout
    command: /start
    volumes:
      - ./scout:/scout
    ports:
      - "127.0.0.1:8012:8000"
    env_file:
      - .env-dev
    depends_on:
      - tor-redis
      - tor-tasks-db
      - tor-scout-api

  tor-scout-api:
    build:
      context: .
      dockerfile: ./compose/local/api/Dockerfile
      args:
        - DEV=true
    image: tor-scout-api
    container_name: tor-scout-api
    command: /start
    volumes:
      - ./api:/api
    ports:
      - "127.0.0.1:8013:8000"
    env_file:
      - .env-dev
    depends_on:
      - tor-websites-db

  tor-celery:
    image: tor-celery
    container_name: tor-celery
    build:
      context: .
      dockerfile: ./compose/local/scout/Dockerfile
    restart: always
    command: /cstart
    volumes:
      - ./scout:/scout
    env_file:
      - .env-dev
    depends_on:
      - tor-scout
      - tor-tasks-db
      - tor-redis

  tor-beat:
    build:
      context: .
      dockerfile: ./compose/local/scout/Dockerfile
    image: tor-beat
    container_name: tor-beat
    command: /bstart
    volumes:
      - ./scout:/scout
    env_file:
      - .env-dev
    depends_on:
      - tor-scout
      - tor-tasks-db
      - tor-redis

  tor-flower:
    build:
      context: .
      dockerfile: ./compose/local/scout/Dockerfile
    image: tor-flower
    container_name: tor-flower
    command: /fstart
    volumes:
      - ./scout:/scout
    env_file:
      - .env-dev
    ports:
      - "127.0.0.1:5559:5555"
    depends_on:
      - tor-scout
      - tor-tasks-db
      - tor-redis

  tor-redis:
    image: redis:7.2.0-alpine
    container_name: tor-redis
    volumes:
      - tor-redis-data-dev:/data

  tor-tasks-db:
    image: postgres:15.4
    container_name: tor-tasks-db
    volumes:
      - tor-task-db-data-dev:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:35432:5432"
    environment:
      - POSTGRES_DB=hello_django
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django

  tor-websites-db:
    image: postgres:15.4
    container_name: tor-websites-db
    volumes:
      - tor-websites-db-data-dev:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:45432:5432"
    environment:
      - POSTGRES_DB=hello_django
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django

  tor-privoxy:
    restart: always
    image: dockage/tor-privoxy:latest
    container_name: tor-privoxy
    ports:
      - "127.0.0.1:9050:9050" # Tor proxy
      - "127.0.0.1:9051:9051" # Tor control port
      - "127.0.0.1:8118:8118" # Privoxy

volumes:
  tor-redis-data-dev:
  tor-task-db-data-dev:
  tor-websites-db-data-dev:
