services:
  search:
    build:
      context: .
      dockerfile: ./compose/local/search/Dockerfile
      network: host
      args:
        - DEV=true
    image: search
    container_name: search
    command: /start
    volumes:
      - ./search:/search
    ports:
      - "127.0.0.1:9002:8000"
    env_file:
      - .env-dev
    depends_on:
      - search-db
      - search-redis
    networks:
      - search-network

  api:
    build:
      context: .
      dockerfile: ./compose/local/api/Dockerfile
      network: host
      args:
        - DEV=true
    image: api
    container_name: api
    command: /start
    volumes:
      - ./api:/api
    ports:
      - "127.0.0.1:9003:8000"
    env_file:
      - .env-dev
    depends_on:
      - api-db
    networks:
      - search-network

  front:
    build:
      context: .
      dockerfile: ./compose/local/front/Dockerfile
      network: host
      args:
        - DEV=true
    image: front
    container_name: front
    command: /start
    volumes:
      - ./front:/front
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env-dev
    depends_on:
      - api
    networks:
      - search-network

  search-db:
    image: postgres:16.2
    container_name: search-db
    volumes:
      - ./local/search/postgres:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:45432:5432"
    environment:
      - POSTGRES_DB=hello_django
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
    networks:
      - search-network

  api-db:
    image: postgres:16.2
    container_name: api-db
    volumes:
      - ./local/api/postgres:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:55432:5432"
    environment:
      - POSTGRES_DB=hello_django
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
    networks:
      - search-network

  search-celery:
    image: search-celery
    container_name: search-celery
    build:
      context: .
      dockerfile: ./compose/local/search/Dockerfile
      network: host
    restart: always
    command: /cstart
    volumes:
      - ./search:/search
    env_file:
      - .env-dev
    depends_on:
      - search-db
      - search-redis
    networks:
      - search-network

  api-celery:
    image: api-celery
    container_name: api-celery
    build:
      context: .
      dockerfile: ./compose/local/api/Dockerfile
      network: host
    restart: always
    command: /cstart
    volumes:
      - ./api:/api
    env_file:
      - .env-dev
    depends_on:
      - api-db
      - search-redis
    networks:
      - search-network

  search-redis:
    image: redis:7.2.0-alpine
    container_name: search-redis
    volumes:
      - ./local/redis:/data
    networks:
      - search-network

  search-beat:
    build:
      context: .
      dockerfile: ./compose/local/search/Dockerfile
      network: host
    image: search-beat
    container_name: search-beat
    command: /bstart
    volumes:
      - ./search:/search
    env_file:
      - .env-dev
    depends_on:
      - search-db
      - search-redis
    networks:
      - search-network

  api-beat:
    build:
      context: .
      dockerfile: ./compose/local/api/Dockerfile
      network: host
    image: api-beat
    container_name: api-beat
    command: /bstart
    volumes:
      - ./api:/api
    env_file:
      - .env-dev
    depends_on:
      - api-db
      - search-redis
    networks:
      - search-network

  search-flower:
    build:
      context: .
      dockerfile: ./compose/local/search/Dockerfile
      network: host
    image: search-flower
    container_name: search-flower
    command: /fstart
    volumes:
      - ./search:/search
    env_file:
      - .env-dev
    ports:
      - "127.0.0.1:5559:5555"
    depends_on:
      - search-db
      - search-redis
    networks:
      - search-network

  api-flower:
    build:
      context: .
      dockerfile: ./compose/local/api/Dockerfile
      network: host
    image: api-flower
    container_name: api-flower
    command: /fstart
    volumes:
      - ./api:/api
    env_file:
      - .env-dev
    ports:
      - "127.0.0.1:5558:5555"
    depends_on:
      - api-db
      - search-redis
    networks:
      - search-network

  search-privoxy:
    restart: always
    image: dockage/tor-privoxy:latest
    container_name: search-privoxy
    ports:
      - "127.0.0.1:9050:9050" # Tor proxy
      - "127.0.0.1:9051:9051" # Tor control port
      - "127.0.0.1:8118:8118" # Privoxy
    networks:
      - search-network

networks:
  search-network:
    name: search-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.95.0/24
