services:
  tor-scout:
    build:
      context: .
      dockerfile: ./compose/local/scout/Dockerfile
      args:
        - DEV=true
    image: tor-scout
    container_name: tor-scout
    command: /start
    volumes:
      - ./scout:/scout
    ports:
      - "127.0.0.1:9002:8000"
    env_file:
      - .env-dev
    depends_on:
      - tor-scout-db
      - tor-scout-redis
    networks:
      - tor-scout

  tor-scout-db:
    image: postgres:16.2
    container_name: tor-scout-db
    volumes:
      - tor-scout-db-data-dev:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:45432:5432"
    environment:
      - POSTGRES_DB=hello_django
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
    networks:
      - tor-scout

  tor-scout-celery:
    image: tor-scout-celery
    container_name: tor-scout-celery
    build:
      context: .
      dockerfile: ./compose/local/scout/Dockerfile
    restart: always
    command: /cstart
    volumes:
      - ./scout:/scout
    env_file:
      - .env-dev
    depends_on:
      - tor-scout-db
      - tor-scout-redis
    networks:
      - tor-scout

  tor-scout-redis:
    image: redis:7.2.0-alpine
    container_name: tor-scout-redis
    volumes:
      - tor-scout-redis-dev:/data
    networks:
      - tor-scout

  tor-scout-beat:
    build:
      context: .
      dockerfile: ./compose/local/scout/Dockerfile
    image: tor-scout-beat
    container_name: tor-scout-beat
    command: /bstart
    volumes:
      - ./scout:/scout
    env_file:
      - .env-dev
    depends_on:
      - tor-scout-db
      - tor-scout-redis
    networks:
      - tor-scout

  tor-scout-flower:
    build:
      context: .
      dockerfile: ./compose/local/scout/Dockerfile
    image: tor-scout-flower
    container_name: tor-scout-flower
    command: /fstart
    volumes:
      - ./scout:/scout
    env_file:
      - .env-dev
    ports:
      - "127.0.0.1:5559:5555"
    depends_on:
      - tor-scout-db
      - tor-scout-redis
    networks:
      - tor-scout

  tor-scout-privoxy:
    restart: always
    image: dockage/tor-privoxy:latest
    container_name: tor-scout-privoxy
    ports:
      - "127.0.0.1:9050:9050" # Tor proxy
      - "127.0.0.1:9051:9051" # Tor control port
      - "127.0.0.1:8118:8118" # Privoxy
    networks:
      - tor-scout

volumes:
  tor-scout-redis-dev:
  tor-scout-db-data-dev:

networks:
  tor-scout:
    name: tor-scout
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.95.0/24
