# Generated by Django 4.2.5 on 2023-09-22 18:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2000, unique=True)),
                ('created', models.IntegerField(blank=True, null=True)),
                ('last_crawl_date', models.IntegerField(blank=True, null=True)),
                ('average_crawl_time', models.IntegerField(blank=True, null=True)),
                ('server', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_crawls_finished', models.IntegerField(default=0)),
                ('number_of_pages_found', models.IntegerField(default=0)),
                ('site_structure', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('url_after_request', models.URLField(max_length=2000)),
                ('last_http_status', models.CharField(blank=True, max_length=3, null=True)),
                ('average_response_time', models.FloatField(blank=True, null=True)),
                ('raw_html', models.TextField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=2000, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=2000, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('on_page_raw_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=2000), blank=True, null=True, size=None)),
                ('on_page_processed_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=2000), blank=True, null=True, size=None)),
                ('number_of_successful_requests', models.IntegerField(blank=True, null=True)),
                ('number_of_unsuccessful_requests', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.IntegerField(blank=True, null=True)),
                ('last_visit', models.IntegerField(blank=True, null=True)),
                ('parent_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawled.domain')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='description_tags',
            field=models.ManyToManyField(to='crawled.tag'),
        ),
        migrations.AddField(
            model_name='domain',
            name='parent_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawled.entity'),
        ),
    ]
