# Generated by Django 5.0.6 on 2024-05-24 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='external_domains_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
