# Generated by Django 4.2.4 on 2023-09-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='website_map',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
