# Generated by Django 4.2.4 on 2023-09-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
