#!/bin/ash

set -o errexit
set -o nounset

worker_ready() {
    celery -A core inspect ping
}

until worker_ready; do
  >&2 echo 'API Service workers are not available...'
  sleep 1
done
>&2 echo 'API Service workers are available!'

celery --broker="${CELERY_BROKER}" flower
