#!/bin/ash


set -o errexit
set -o pipefail
set -o nounset


python manage.py makemigrations
python manage.py migrate
python manage.py prepare
python manage.py collectstatic --noinput
uvicorn core.asgi:application --reload --host 0.0.0.0 --port 8000
