#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --noinput
python manage.py prepare
#uvicorn core.asgi:application --reload --host 0.0.0.0 --port 8000
gunicorn -k uvicorn.workers.UvicornWorker core.asgi:application --workers 4 --bind 0.0.0.0:8000
