# Generated by Django 4.2.4 on 2023-09-10 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DOMAIN', 'Domain')], default='DOMAIN', max_length=10)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running')], default='IDLE', max_length=20)),
                ('importance', models.IntegerField(default=1)),
                ('last_run', models.IntegerField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='domains.domain')),
            ],
        ),
    ]
