# Generated by Django 4.2.4 on 2023-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3000, unique=True)),
                ('url', models.URLField(blank=True, max_length=3000, null=True, unique=True)),
            ],
        ),
    ]
