# Generated by Django 5.0.6 on 2024-07-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
                ('proxy_type', models.CharField(choices=[('DEV', 'Dev'), ('PRODUCTION', 'Production')], default='DEV', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=10)),
                ('current_spiders', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Proxies',
                'db_table': 'proxies',
                'db_table_comment': 'Proxies information.',
            },
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHROME', 'Chrome'), ('FIREFOX', 'Firefox')], default='FIREFOX', max_length=10)),
                ('value', models.CharField(default=None, max_length=255, unique=True)),
                ('created', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'UserAgents',
                'db_table': 'user-agents',
                'db_table_comment': 'User Agents for many browsers.',
            },
        ),
    ]
