# Generated by Django 5.0.3 on 2024-04-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEV', 'Dev'), ('PRODUCTION', 'Production')], default='DEV', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=10)),
                ('value', models.CharField(default=None, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHROME', 'Chrome'), ('FIREFOX', 'Firefox')], default='FIREFOX', max_length=10)),
                ('value', models.CharField(default=None, max_length=255, unique=True)),
                ('created', models.IntegerField()),
            ],
        ),
    ]
